---
language: bash

env:
  - TERRAFORM_VERSION=latest

branches:
  only:
    - master

install:
  # Install Terraform.
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

script:
  # Check the syntax of terraform
  #- cd env/dev/ && terraform init
  #- cd env/dev/ && terraform validate
  - terraform validate
  - |
  for example in $(find env/dev -maxdepth 1 -mindepth 1 -type d); do
  cd $example
  terraform init
  terraform fmt -check=true
  terraform validate
  done
  - terraform -v
 
