---
language: bash

env:
  - TERRAFORM_VERSION=latest

branches:
  only:
    - master

install:
  # Install Terraform.
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

script:
  # Check the syntax of terraform
  - terraform validate VPC"
